[platformio]
default_envs = romeo
[env:romeo]
platform = espressif32@6.5.0
board = dfrobot_romeo_esp32s3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = earlephilhower/ESP8266Audio@1.9.7
