[platformio]
default_envs = feather
[env:feather]
platform = espressif32@6.5.0
board = featheresp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = earlephilhower/ESP8266Audio@1.9.7
